### ISSUE TITLE
Error with the .env

### ISSUE THREAD

**Issue by Hilsey01** [niekcandaele/CSGO-RankMe-stats#1]
Hello, i am new to using java script and i came across an error when i was naming the .env.example to .env it wouldn't let me name it and it said "you must type a file name"  so i tried naming it database.env and that still didn't work giving me an error: 
![image](https://user-images.githubusercontent.com/44524688/47603907-7ac36300-d9ea-11e8-90eb-10f47ddc73fd.png)

i changed the database to not be localhost and instead the database ip but it is still showing up as localhost or 127.0.0.1:3306

Thanks for making the awesome bot, hopefully speak soon!

**Comment by niekcandaele** [comment]
Hey there, sorry for the late reply. Somehow the notification slipped by me!

It looks like you are hosting on windows which is a little prickly about file names/extensions. Maybe [this stackoverflow post](https://stackoverflow.com/questions/5004633/how-to-manually-create-a-file-with-a-dot-prefix-in-windows-for-example-htacce/5004695#5004695) can help you on your way.

If you have git bash installed, you can use the command `cp .env.example .env`.

The errors you get in the screenshot is because there is no valid .env file. Once you get that sorted it should be no problem

**Comment by niekcandaele** [comment]
Feel free to [join my discord server](http://catalysm.net/discord) if you need realtime help, I'll answer faster there :)

**Comment by niekcandaele** [comment]
Closed for inactivity
